# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PyGeoRS
                                 A QGIS plugin
 This plugin automates remote sensing tasks
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-09-24
        copyright            : (C) 2023 by Dr. Anass MARZOUKI
        email                : anass.marzouki@usmba.ac.ma
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PyGeoRS class from file PyGeoRS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .PyGeoRS import PyGeoRS
    return PyGeoRS(iface)
